name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install test dependencies
        run: pip install -r tests/requirements.txt

      - name: Run tests
        run: pytest tests/test_health.py tests/test_input_validator.py tests/test_auth_guard.py tests/test_api_integration.py::TestAPIIntegration::test_health_endpoint -v